version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3005:3005"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: ["--bind_ip_all"]
    volumes:
    - ./data:/data/db
    ports:
      - "27017:27017"